server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://xd-mau5.xyz/admin_powerup
    username: admin_powerup
    password: Powerup1234
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"

auth:
  api:
    url: http://xd-mau5.xyz:8090/