server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://xd-mau5.xyz/admin_powerup
    username: admin_powerup
    password: Powerup1234
  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      auto-index-creation: true
      database: plaza
      authentication-database: admin
      host: xd-mau5.xyz
      port: 27017
      username: plaza
      password: Powerup1234


jwt:
  secret: ${KEYSECRET_SECURITY:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA}
management:
  endpoints:
    web:
      exposure:
        include: "*"

auth:
  api:
    url: http://xd-mau5.xyz:8090/
message:
  api:
    url: http://xd-mau5.xyz:8093/
